INSERT INTO TEACHER VALUES (1, 'teacher', 'teacher');
INSERT INTO ADMIN VALUES (1, 'admin', 'admin');
INSERT INTO STUDENT VALUES (1, 'student', 'student');
INSERT INTO COURSE VALUES (1, '课程1');
INSERT INTO COURSE_TEACHER VALUES (1, 1, 1);
INSERT INTO HOMEWORK VALUES (1, 1, '作业1', 'path', '2017-8-11 09:08');